name: CI - Web Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate index.html exists
        run: |
          if [ -f "index.html" ]; then
            echo "✅ index.html ditemukan!"
          else
            echo "❌ File index.html tidak ditemukan!"
            exit 1
          fi

      - name: Check NIM in HTML
        run: |
          if grep -q "230411100124" index.html; then
            echo "✅ NIM ditemukan dalam file HTML"
          else
            echo "❌ NIM tidak ditemukan!"
            exit 1
          fi
